//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF_Bolnica.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacijent
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Odjel { get; set; }
        public string Kriticnost { get; set; }
        public string Stacioniran { get; set; }
    }
}
