//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AČ_Playlista.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pjesma
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Autor { get; set; }
        public string Duljina { get; set; }
        public string Distribucija { get; set; }
        public string Eksplicitno { get; set; }
        public string Grammy { get; set; }
    }
}
