//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ČičaZAVRŠNI_Programiranje.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrafickaKartica
    {
        public int Id { get; set; }
        public string Marka { get; set; }
        public string MjesecDostave { get; set; }
        public string BrojMjeseci { get; set; }
        public string Rezervirana { get; set; }
        public string Odjeljak { get; set; }
    }
}
