//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dario_Golubović__Popis_arhitekata.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arhitekt
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Zvanje { get; set; }
        public string GodineIskustva { get; set; }
        public string Zauzet { get; set; }
    }
}
