//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkoKaratur_TrgovineNTL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trgovine
    {
        // klasa Trgovine i njezini property-i
        public int Id { get; set; }
        public string ImeTrgovine { get; set; }
        public string Lokacija { get; set; }
        public string BrojRadnika { get; set; }
        public string Kategorija { get; set; }
    }
}
