//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ivamatasic_Odvjetnici.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odvjetnik
    {
        // Odvjetnik entitet sa svojim property-ima (služi kao kalup za unos u bazu)
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Godine { get; set; }
        public string TICOugovor { get; set; }
        public string Posudba { get; set; }
        public string Razina { get; set; }
    }
}
